# Generated by Django 4.2.25 on 2025-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_dataset_uploadeddataset_trainedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasemodel',
            name='feature_importance',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
