# Generated by Django 4.2.25 on 2025-10-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_diseasemodel_feature_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='feature_importance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
