# Generated by Django 4.2.25 on 2025-10-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trainedmodel_feature_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='disease_type',
            field=models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('heart_disease', 'Heart Disease'), ('ckd', 'Chronic Kidney Disease'), ('copd', 'COPD'), ('asthma', 'Asthma')], default='diabetes', help_text='Select which disease this model predicts', max_length=50),
        ),
    ]
